[project]
name = "scapyra"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "numpy>=2.3.4",
    "pytest>=8.4.2",
    "typer>=0.20.0",
]

[project.scripts]
scapyra = "ScaPyra.cli:app"
